#!/bin/bash
echo "#############################################"
echo "##"
echo "## Starting mopidy ... "
echo "##"
echo "#############################################"

echo "## scan local ... "
/usr/bin/mopidy --config /etc/mopidy/mopidy.conf local scan

echo "## start server ... "
exec /usr/bin/mopidy --config /etc/mopidy/mopidy.conf
