FROM debian:10

COPY snapserver/install /install
COPY snapserver/docker-entrypoint.sh /
RUN bash /install/install.sh

COPY snapserver/snapserver.conf /etc/snapserver.conf
COPY snapserver/index.html /www/index.html

ENTRYPOINT /docker-entrypoint.sh
