version: '3'
services:
  mopidy:
    restart: always
    image: rmalchow/mopidy
    hostname: ${hostname}-mopidy
    expose:
      - 6600
      - 6680
    ports:
      - "6600:6600"
      - "6680:6680"
    volumes:
      - ${home}/soundshare:/tmp/snapcast
      - ${home}/config/mopidy.conf:/etc/mopidy/mopidy.conf
      #- /home/rm/Desktop/music:/var/lib/mopidy/media
    #network_mode: host
